{{ if and .Values.service.port .Values.overlord.db_url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "overlord.fullname" . }}-secret
  labels:
    {{- include "overlord.labels" . | nindent 4 }}
type: Opaque
data:
  port: {{ .Values.service.port | b64enc }}
  db_url: {{ .Values.overlord.db_url | b64enc }}
{{ end }}