// Code generated by scripts/build-reference-specs.py. DO NOT EDIT.
//
// Sourced from Wikidata, which is CC0, so these facts carry no attribution or
// share-alike obligation. Values are whatever Wikidata actually holds: coverage
// is uneven, absent fields are omitted rather than guessed, and numbers in an
// unexpected unit are dropped rather than converted blindly. QID is recorded so
// any value can be traced back to its entity.
//
// Regenerate with: python scripts/build-reference-specs.py

package models

// Specs holds the physical facts for one type. Zero values mean "not recorded".
type Specs struct {
	QID           string
	LengthM       float64
	WingspanM     float64
	HeightM       float64
	MassKg        float64
	FirstFlight   string
	ServiceEntry  string
	TotalProduced int
	Makers        []string
}

var unitSpecs = map[string]Specs{
	"A-10A":                {QID: "Q192443", LengthM: 16.56, WingspanM: 17.53, FirstFlight: "1972-05-10", ServiceEntry: "1977", TotalProduced: 716, Makers: []string{"Fairchild Republic"}},
	"A-10C":                {QID: "Q192443", LengthM: 16.56, WingspanM: 17.53, FirstFlight: "1972-05-10", ServiceEntry: "1977", TotalProduced: 716, Makers: []string{"Fairchild Republic"}},
	"A-50":                 {QID: "Q499185", LengthM: 49.59, WingspanM: 50.5, HeightM: 14.76, MassKg: 75000, FirstFlight: "1978-12-19", ServiceEntry: "1989", TotalProduced: 40, Makers: []string{"Beriev", "Tashkent Mechanical Plant"}},
	"AH-64A":               {QID: "Q171468", LengthM: 14.68, HeightM: 4.72, FirstFlight: "1975-09-30", ServiceEntry: "1984-01-26", TotalProduced: 2000, Makers: []string{"Hughes Helicopters", "McDonnell Douglas", "Boeing Defense, Space & Security", "AgustaWestland"}},
	"AH-64D":               {QID: "Q171468", LengthM: 14.68, HeightM: 4.72, FirstFlight: "1975-09-30", ServiceEntry: "1984-01-26", TotalProduced: 2000, Makers: []string{"Hughes Helicopters", "McDonnell Douglas", "Boeing Defense, Space & Security", "AgustaWestland"}},
	"AJS37":                {QID: "Q263786", LengthM: 16.3, WingspanM: 10.6, FirstFlight: "1967-02-08", ServiceEntry: "1972-01-01", TotalProduced: 330, Makers: []string{"Saab Group"}},
	"AV8BNA":               {QID: "Q635687", LengthM: 14.12, WingspanM: 9.25, HeightM: 3.55, MassKg: 6764, FirstFlight: "1978-11-09", ServiceEntry: "1985-01", TotalProduced: 337, Makers: []string{"McDonnell Douglas", "BAE Systems"}},
	"An-26B":               {QID: "Q62156", FirstFlight: "1969-05-21", ServiceEntry: "1973", TotalProduced: 1403, Makers: []string{"Antonov", "Antonov Serial Production Plant"}},
	"BMP-2":                {QID: "Q160357", LengthM: 6.72, HeightM: 2.45, MassKg: 14300, ServiceEntry: "1980-01-01", TotalProduced: 11130, Makers: []string{"Kurganmashzavod", "Cestné a Stavebné Mechanizmy Tisovec"}},
	"BTR-80":               {QID: "Q477818", LengthM: 7.65, HeightM: 2.35, MassKg: 13600, ServiceEntry: "1986-01-01", TotalProduced: 4300, Makers: []string{"GAZ"}},
	"C-130":                {QID: "Q182027", LengthM: 29.78, WingspanM: 40.41, HeightM: 11.66, FirstFlight: "1954-08-23", ServiceEntry: "1956", TotalProduced: 2600, Makers: []string{"Lockheed Corporation", "Lockheed Martin"}},
	"C-17A":                {QID: "Q211369", LengthM: 53, WingspanM: 52, HeightM: 16.79, FirstFlight: "1991-09-15", ServiceEntry: "1995-01-17", TotalProduced: 279, Makers: []string{"Boeing", "McDonnell Douglas"}},
	"CH-47D":               {QID: "Q209613", LengthM: 30.1, HeightM: 5.7, FirstFlight: "1961-09-21", ServiceEntry: "1962", TotalProduced: 1200, Makers: []string{"Boeing Defense, Space & Security", "Boeing", "Pennsylvania", "AgustaWestland", "Kawasaki Heavy Industries"}},
	"E-3A":                 {QID: "Q261384", LengthM: 46.61, WingspanM: 44.42, FirstFlight: "1972-02-09", ServiceEntry: "1977-03", TotalProduced: 68, Makers: []string{"Boeing Defense, Space & Security", "Westinghouse Electric Corporation"}},
	"F-14B":                {QID: "Q34945", LengthM: 19, WingspanM: 19.55, HeightM: 4.8, FirstFlight: "1970-12-21", ServiceEntry: "1974", TotalProduced: 712, Makers: []string{"Grumman"}},
	"F-15C":                {QID: "Q29251", LengthM: 19.44, WingspanM: 13, HeightM: 5.6, FirstFlight: "1972-07-27", ServiceEntry: "1976-01-09", TotalProduced: 1198, Makers: []string{"McDonnell Douglas", "Boeing"}},
	"F-15E":                {QID: "Q844500", LengthM: 19.44, WingspanM: 13, HeightM: 5.6, MassKg: 17010, FirstFlight: "1986-12-11", ServiceEntry: "1988-12", TotalProduced: 470, Makers: []string{"McDonnell Douglas", "Boeing Defense, Space & Security", "Boeing"}},
	"F-16C_50":             {QID: "Q100026", LengthM: 15.06, WingspanM: 9.96, HeightM: 4.88, FirstFlight: "1974-01-20", ServiceEntry: "1979", TotalProduced: 4573, Makers: []string{"General Dynamics", "Lockheed Martin", "SABCA", "Fokker", "Turkish Aerospace Industries", "Samsung Aerospace", "Lockheed Corporation"}},
	"F-4E":                 {QID: "Q151432", LengthM: 19.2, WingspanM: 11.68, HeightM: 5, FirstFlight: "1958-05-27", ServiceEntry: "1959", TotalProduced: 5195, Makers: []string{"McDonnell Aircraft Corporation", "McDonnell Douglas"}},
	"FA-18C_hornet":        {QID: "Q46397", LengthM: 17.1, HeightM: 4.9, FirstFlight: "1978-11-18", ServiceEntry: "1983-01-07", TotalProduced: 1480, Makers: []string{"McDonnell Douglas", "Boeing Defense, Space & Security", "Boeing"}},
	"Hawk tr":              {QID: "Q482414", Makers: []string{"Raytheon"}},
	"IL-76MD":              {QID: "Q142549", LengthM: 46.59, WingspanM: 50.5, FirstFlight: "1971-03-25", ServiceEntry: "1974", TotalProduced: 950, Makers: []string{"Ilyushin", "Tashkent Mechanical Plant", "Aviastar-SP"}},
	"IL-78M":               {QID: "Q182617", FirstFlight: "1983-06-26", ServiceEntry: "1985", TotalProduced: 53, Makers: []string{"Ilyushin", "Tashkent Mechanical Plant", "Aviastar-SP"}},
	"KC-135":               {QID: "Q829092", LengthM: 41.5, WingspanM: 39.88, HeightM: 12.7, FirstFlight: "1956-08-31", ServiceEntry: "1957-06", TotalProduced: 803, Makers: []string{"Boeing"}},
	"Ka-50":                {QID: "Q269250", LengthM: 16, HeightM: 5.4, FirstFlight: "1982-06-17", ServiceEntry: "1995-08-28", TotalProduced: 16, Makers: []string{"Kamov"}},
	"M-1 Abrams":           {QID: "Q173684", MassKg: 54000, ServiceEntry: "1980-01-01", TotalProduced: 10288, Makers: []string{"Joint Systems Manufacturing Center", "Detroit Arsenal Tank Plant", "General Dynamics"}},
	"M-2 Bradley":          {QID: "Q473430", LengthM: 6.55, HeightM: 2.98, MassKg: 30400, ServiceEntry: "1981-01-01", Makers: []string{"BAE Systems"}},
	"M-2000C":              {QID: "Q200038", LengthM: 14.36, WingspanM: 9, HeightM: 5.3, FirstFlight: "1978-03-10", ServiceEntry: "1984-07-02", TotalProduced: 601, Makers: []string{"Dassault Aviation"}},
	"M1097 Avenger":        {QID: "Q589281", ServiceEntry: "1989-01-01", Makers: []string{"Boeing"}},
	"Mi-24P":               {QID: "Q155651", LengthM: 17.5, HeightM: 6.5, FirstFlight: "1969-09-19", ServiceEntry: "1969", TotalProduced: 2300, Makers: []string{"Mil Moscow Helicopter Plant", "Rostvertol"}},
	"Mi-26":                {QID: "Q336150", LengthM: 33.7, FirstFlight: "1977-12-14", ServiceEntry: "1985", TotalProduced: 318, Makers: []string{"Mil Moscow Helicopter Plant", "Rostvertol"}},
	"Mi-8MT":               {QID: "Q155635", LengthM: 18.17, HeightM: 5.65, FirstFlight: "1961-07-07", ServiceEntry: "1965", TotalProduced: 12000, Makers: []string{"Mil Moscow Helicopter Plant", "Kazan Helicopters", "Ulan-Ude Aviation Plant"}},
	"MiG-21Bis":            {QID: "Q150609", LengthM: 15.76, WingspanM: 7.15, HeightM: 4.12, FirstFlight: "1956-02-14", ServiceEntry: "1959", Makers: []string{"Russian Aircraft Corporation MiG", "Sokol", "Dux Factory", "Tbilisi Aircraft Manufacturing", "AERO Vodochody Aerospace", "Hindustan Aeronautics Limited", "Chengdu Aircraft Industry Group"}},
	"MiG-29S":              {QID: "Q130681", LengthM: 17.37, WingspanM: 11.4, HeightM: 4.73, FirstFlight: "1977-10-06", ServiceEntry: "1983-07", TotalProduced: 1600, Makers: []string{"Russian Aircraft Corporation MiG", "Dux Factory", "Sokol"}},
	"MiG-31":               {QID: "Q150050", LengthM: 22.69, WingspanM: 13.46, HeightM: 6.15, FirstFlight: "1975-09-16", ServiceEntry: "1981-05-06", TotalProduced: 519, Makers: []string{"Russian Aircraft Corporation MiG", "Sokol"}},
	"Roland ADS":           {QID: "Q705254", TotalProduced: 650, Makers: []string{"Euromissile"}},
	"SA-11 Buk LN 9A310M1": {QID: "Q950158", LengthM: 5.55, ServiceEntry: "1979-01-01"},
	"SA342M":               {QID: "Q794595", LengthM: 11.97, HeightM: 3.15, FirstFlight: "1967-04-07", ServiceEntry: "1973", TotalProduced: 1775, Makers: []string{"Aérospatiale", "Airbus Helicopters", "SOKO"}},
	"Strela-10M3":          {QID: "Q633510", MassKg: 41, ServiceEntry: "1979-01-01", Makers: []string{"Saratovsky Zenit Machine Plant", "LOMO"}},
	"Su-24M":               {QID: "Q210413", LengthM: 22.53, WingspanM: 17.5, HeightM: 6.19, FirstFlight: "1970-01-17", ServiceEntry: "1975-02-04", Makers: []string{"Sukhoi", "Novosibirsk Aircraft Production Association"}},
	"Su-25":                {QID: "Q192137", LengthM: 14.5, WingspanM: 14.3, HeightM: 4.95, FirstFlight: "1975-02-22", ServiceEntry: "1981", TotalProduced: 1320, Makers: []string{"Sukhoi", "Tbilisi Aircraft Manufacturing", "Ulan-Ude Aviation Plant"}},
	"Su-25T":               {QID: "Q192137", LengthM: 14.5, WingspanM: 14.3, HeightM: 4.95, FirstFlight: "1975-02-22", ServiceEntry: "1981", TotalProduced: 1320, Makers: []string{"Sukhoi", "Tbilisi Aircraft Manufacturing", "Ulan-Ude Aviation Plant"}},
	"Su-27":                {QID: "Q173680", LengthM: 21.9, WingspanM: 14.7, HeightM: 5.93, FirstFlight: "1977-05-20", ServiceEntry: "1985", TotalProduced: 809, Makers: []string{"Sukhoi", "Komsomolsk-on-Amur Aircraft Production Association"}},
	"Su-33":                {QID: "Q332637", FirstFlight: "1987-08-17", ServiceEntry: "1998-08-31", Makers: []string{"Sukhoi", "Komsomolsk-on-Amur Aircraft Production Association"}},
	"Su-34":                {QID: "Q309177", LengthM: 23.3, WingspanM: 14.7, HeightM: 6.09, FirstFlight: "1990-04-13", ServiceEntry: "2014-03-21", TotalProduced: 143, Makers: []string{"Sukhoi", "Novosibirsk Aircraft Production Association"}},
	"T-72B":                {QID: "Q155658", HeightM: 2.37, ServiceEntry: "1973-01-01", TotalProduced: 25000, Makers: []string{"Uralvagonzavod"}},
	"T-80UD":               {QID: "Q237135", LengthM: 7.01, HeightM: 2.2, MassKg: 46000, ServiceEntry: "1976-01-01", TotalProduced: 9500, Makers: []string{"Kirov Plant", "Omsktransmash"}},
	"Tor 9A331":            {QID: "Q756212", LengthM: 3.5, HeightM: 5.1, MassKg: 167, ServiceEntry: "1986-01-01", Makers: []string{"Izhevsk Electromechanical Plant"}},
	"Tu-22M3":              {QID: "Q204944", LengthM: 39.5, WingspanM: 34.3, FirstFlight: "1969-08-30", ServiceEntry: "1976", TotalProduced: 497, Makers: []string{"Tupolev", "Kazan Aircraft Production Association"}},
	"Tu-95MS":              {QID: "Q181815", LengthM: 46.2, WingspanM: 50.1, HeightM: 12.12, FirstFlight: "1952-11-12", ServiceEntry: "1956-04", TotalProduced: 500, Makers: []string{"Tupolev", "Aviakor", "Taganrog aviation"}},
	"UH-60A":               {QID: "Q189491", FirstFlight: "1974-10-17", ServiceEntry: "1979", TotalProduced: 4000, Makers: []string{"Sikorsky Aircraft Corporation"}},
}

var weaponSpecs = map[string]Specs{
	"AGM_114K":                       {QID: "Q271930", LengthM: 1.63, ServiceEntry: "1984-01-01", Makers: []string{"Lockheed Martin"}},
	"AGM_154":                        {QID: "Q210751", Makers: []string{"Raytheon"}},
	"AGM_65D":                        {QID: "Q292553", LengthM: 2.49, ServiceEntry: "1972-08-30", TotalProduced: 70000, Makers: []string{"Hughes Aircraft Company", "Raytheon"}},
	"AGM_65H":                        {QID: "Q292553", LengthM: 2.49, ServiceEntry: "1972-08-30", TotalProduced: 70000, Makers: []string{"Hughes Aircraft Company", "Raytheon"}},
	"AGM_88":                         {QID: "Q292601", MassKg: 360, ServiceEntry: "1985-01-01", Makers: []string{"Texas Instruments", "Raytheon"}},
	"AIM_120":                        {QID: "Q293743", LengthM: 3.66, MassKg: 157, ServiceEntry: "1991", TotalProduced: 20000, Makers: []string{"Raytheon"}},
	"AIM_120C":                       {QID: "Q293743", LengthM: 3.66, MassKg: 157, ServiceEntry: "1991", TotalProduced: 20000, Makers: []string{"Raytheon"}},
	"AIM_54C_Mk47":                   {QID: "Q293772", ServiceEntry: "1974-01-01", Makers: []string{"Hughes Aircraft Company", "Raytheon"}},
	"AIM_7":                          {QID: "Q293810", LengthM: 3.7, MassKg: 231, ServiceEntry: "1956", Makers: []string{"Raytheon"}},
	"AIM_9":                          {QID: "Q235396", ServiceEntry: "1956-01-01", Makers: []string{"Raytheon", "RTX"}},
	"AIM_9X":                         {QID: "Q235396", ServiceEntry: "1956-01-01", Makers: []string{"Raytheon", "RTX"}},
	"AT_6":                           {QID: "Q298671", ServiceEntry: "1976", Makers: []string{"KBM"}},
	"FIM_92C":                        {QID: "Q223697", LengthM: 1.52, MassKg: 15.2, ServiceEntry: "1981-01-01", Makers: []string{"General Dynamics", "Raytheon"}},
	"GBU_12":                         {QID: "Q1335231"},
	"GBU_31":                         {QID: "Q903190", ServiceEntry: "1997-01-01", TotalProduced: 500000, Makers: []string{"Boeing", "McDonnell Douglas"}},
	"GBU_38":                         {QID: "Q903190", ServiceEntry: "1997-01-01", TotalProduced: 500000, Makers: []string{"Boeing", "McDonnell Douglas"}},
	"KONKURS":                        {QID: "Q298659", MassKg: 14.6, ServiceEntry: "1974-01-01", Makers: []string{"KBP Instrument Design Bureau", "Tula Arms Plant"}},
	"P_27P":                          {QID: "Q830126", ServiceEntry: "1983-01-01", Makers: []string{"Vympel"}},
	"P_27PE":                         {QID: "Q830126", ServiceEntry: "1983-01-01", Makers: []string{"Vympel"}},
	"P_27TE":                         {QID: "Q830126", ServiceEntry: "1983-01-01", Makers: []string{"Vympel"}},
	"P_33E":                          {QID: "Q930761", ServiceEntry: "1981-01-01", Makers: []string{"Vympel"}},
	"P_40T":                          {QID: "Q1072287", ServiceEntry: "1970-01-01", Makers: []string{"Vympel"}},
	"P_60":                           {QID: "Q930873", LengthM: 2.09, MassKg: 43.5, ServiceEntry: "1974-01-01", Makers: []string{"Vympel"}},
	"P_73":                           {QID: "Q752536", LengthM: 2.9, MassKg: 105, ServiceEntry: "1982-01-01", Makers: []string{"Vympel"}},
	"RBK_250":                        {QID: "Q4386460"},
	"ROLAND_R":                       {QID: "Q705254", TotalProduced: 650, Makers: []string{"Euromissile"}},
	"SA9M330":                        {QID: "Q756212", LengthM: 3.5, HeightM: 5.1, MassKg: 167, ServiceEntry: "1986-01-01", Makers: []string{"Izhevsk Electromechanical Plant"}},
	"SA9M333":                        {QID: "Q633510", MassKg: 41, ServiceEntry: "1979-01-01", Makers: []string{"Saratovsky Zenit Machine Plant", "LOMO"}},
	"SA9M38M1":                       {QID: "Q950158", LengthM: 5.55, ServiceEntry: "1979-01-01"},
	"TOW2":                           {QID: "Q747313", ServiceEntry: "1970-01-01", Makers: []string{"Raytheon"}},
	"X_25MP":                         {QID: "Q296988", ServiceEntry: "1975-01-01"},
	"X_31P":                          {QID: "Q297043", ServiceEntry: "1988-01-01", Makers: []string{"Tactical Missiles Corporation"}},
	"X_58":                           {QID: "Q255560", ServiceEntry: "1982-01-01", Makers: []string{"MKB Raduga"}},
	"weapons.shells.2A42_30_AP":      {QID: "Q937772", Makers: []string{"Tulamashzavod"}},
	"weapons.shells.2A42_30_HE":      {QID: "Q937772", Makers: []string{"Tulamashzavod"}},
	"weapons.shells.M242_25_AP_M791": {QID: "Q138729", ServiceEntry: "1972-01-01", TotalProduced: 10500, Makers: []string{"Alliant Techsystems"}},
	"weapons.shells.M242_25_HE_M792": {QID: "Q138729", ServiceEntry: "1972-01-01", TotalProduced: 10500, Makers: []string{"Alliant Techsystems"}},
	"weapons.shells.M256_120_AP":     {QID: "Q109592458"},
	"weapons.shells.M256_120_HE":     {QID: "Q109592458"},
	"weapons.shells.M2_12_7":         {QID: "Q218932", ServiceEntry: "1933-01-01", TotalProduced: 3000000, Makers: []string{"General Dynamics", "U.S. Ordnance", "FN Herstal"}},
	"weapons.shells.M2_12_7_T":       {QID: "Q218932", ServiceEntry: "1933-01-01", TotalProduced: 3000000, Makers: []string{"General Dynamics", "U.S. Ordnance", "FN Herstal"}},
	"weapons.shells.M61_20_HE":       {QID: "Q725972", MassKg: 112.92, ServiceEntry: "1959-01-01", Makers: []string{"General Electric", "General Dynamics"}},
}
